name: build-tag-deploy
on:
  push:
    branches: [ main, feature/demo/DEL-40 ]
permissions:
  contents: write
jobs:
  build-tag-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Install and Build ðŸ”§
        working-directory: ./app
        run: |
          npm ci
          npm run build
          cp .gitignore ../.gitignore

      - name: Bump and Tag ðŸ·ï¸
        working-directory: ./app
        run: |
          npm version patch
          git config user.email "jamesrichardsmith97@gmail.com"
          git config user.name "JRSmiffy"
          echo "VERSION=$(cat package.json | jq -r '.version')" >> $VERSION
          git tag "$($VERSION)" -m "[release] delaunay-$($VERSION)"
#          git push origin "$(cat package.json | jq -r '.version')"
      # set env var for version and reuse...
      # set git config higher up?

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $VERSION

      - name: Add -SNAPSHOT ðŸ“·
        working-directory: ./app
        run: |
          npm version patch --git-tag-version false
          npm version $(cat package.json | jq -r '.version')-SNAPSHOT

      - name: Commit -SNAPSHOT ðŸ’¾
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .

# Courtesy of:
# https://github.com/marketplace/actions/deploy-to-github-pages
# https://github.com/marketplace/actions/git-auto-commit

# TODO: rm css and js again! .gitignore copy in the wrong place (need twice?)