name: build-tag-deploy
on:
  push:
    branches: [ main, feature/demo/DEL-40 ]
permissions:
  contents: write
jobs:
  build-tag-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§
        working-directory: ./app
        run: |
          npm ci
          npm run build
          cp .gitignore ../.gitignore

#      - name: Bump and Tag ğŸ·ï¸ # replace with a simple npm version and commit msg "[release] delaunay-$(cat package.json | jq -r '.version')"
#        uses: phips28/gh-action-bump-version@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PACKAGEJSON_DIR: './app'

      - name: Bump and Tag ğŸ·ï¸
        working-directory: ./app
        run: |
          npm version patch
          git config user.email "jamesrichardsmith97@gmail.com"
          git config user.name "JRSmiffy"
          git tag "v$(cat package.json | jq -r '.version')" -m "[release] delaunay-$(cat package.json | jq -r '.version')"
          git push origin "v$(cat package.json | jq -r '.version')"

      - name: Commit Tag (X)
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Add -SNAPSHOT ğŸ“·
        working-directory: ./app
        run: |
          npm version patch --git-tag-version false
          npm version $(cat package.json | jq -r '.version')-SNAPSHOT

      - name: Commit -SNAPSHOT ğŸ’¾
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .

# Courtesy of:
# https://github.com/marketplace/actions/deploy-to-github-pages
# https://github.com/marketplace/actions/automated-version-bump
# https://github.com/marketplace/actions/git-auto-commit

# Note :: Use of the following commit-words will cause bumps according to their level
# majorWords: [ 'BREAKING CHANGE', 'major' ],
# minorWords: [ 'feat', 'minor' ],
# patchWords: null,
# preReleaseWords: [ 'pre-alpha', 'pre-beta', 'pre-rc' ]


# TODO: rm css and js again! .gitignore copy in the wrong place (need twice?)