name: build-tag-deploy
on:
  push:
    branches: [ main, feature/demo/DEL-40 ]
permissions:
  contents: write
jobs:
  build-deploy-tag:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§
        working-directory: ./app
        run: |
          npm ci
          npm run build
          cp .gitignore ../.gitignore

      - name: Bump and Tag ğŸ·ï¸
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: './app'

      - name: Add -SNAPSHOT (X) # TODO
        working-directory: ./app
        run: |
          npm version $(cat package.json | jq -r '.version')-SNAPSHOT

      - name: Commit -SNAPSHOT (X) # TODO
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .

# Courtesy of:
# https://github.com/marketplace/actions/deploy-to-github-pages
# https://github.com/marketplace/actions/automated-version-bump
# ... TODO