name: build-deploy-tag
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build-deploy-tag:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§
        working-directory: ./app
        run: |
          npm ci
          npm run build
          cp .gitignore ../.gitignore

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .

      - name: Bump and Tag ğŸ·ï¸
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: './app'
        with:
          major-wording: '[major]'
          minor-wording: '[minor]'
          patch-wording: '[patch]'

# Courtesy of:
# https://github.com/marketplace/actions/deploy-to-github-pages
# https://github.com/marketplace/actions/automated-version-bump